name: Build ROM
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "Official ROM URL"
        required: true
        default: "https://bn.d.miui.com/OS1.0.18.0.UMLCNXM/miui_COROT_OS1.0.18.0.UMLCNXM_a086066b44_14.0.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-docker-images: "true" # Remove unused Docker images
          remove-codeql: "true" # Remove CodeQL components
      - name: Checkout repos
        uses: actions/checkout@main
      - name: Setup
        run: |
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          sudo bash setup.sh
      - name: Build
        run: |
          sudo bash build.sh "${{ github.event.inputs.URL }}" "${GITHUB_ENV}"
      - name: Upload ROM
        run: |
          User="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          url2=$(curl -s https://api.gofile.io/servers | jq -r '.data.servers[0].name')
          [ -z "$url2" ] && url2="store$(( $RANDOM % 8 + 1 ))"
          Linkrom="$(curl --dns-servers '1.1.1.1' -L -N -H "$User" -F "file=@${{ env.rom_path }}" "https://${url2}.gofile.io/contents/uploadFile" | jq -r .data.downloadPage)"
          sudo echo -e "- Link ROM: $Linkrom" | tee "${GITHUB_WORKSPACE}/out/build.log"
      - name: Upload GitHub Release
        uses: ncipollo/release-action@main
        with:
          name: ${{ env.os_version }}
          tag: ${{ env.os_version }}
          bodyFile: "${{ github.workspace }}/build.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
