name: Build ROM
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的底包/xiaomi.eu底包下载地址"
        required: true
        default: 'https://008686.xyz/f/NZ3ug/miui_HAYDN_OS1.0.2.0.UKKCNXM_2fa8bde61d_14.0.zip'
        
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 最大化构建环境
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: 1.准备环境
        run: |
          sudo apt install aria2 python3 busybox zip tar apktool unzip p7zip-full zipalign zstd bc android-sdk-libsparse-utils xmlstarlet
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome requests setuptools docopt
      - name: 2.克隆仓库
        run: |
          git clone --depth 1 https://github.com/tosasitill/hyperos_action hyperos_port
          aria2c -s 10 -x 10 -o devices.zip -d ./hyperos_port "${{ secrets.LINK }}"
          cd hyperos_port
          mkdir devices && cd devices
          7z x ../devices.zip && cd .. && rm -rf devices.zip
      - name: 3. 开始移植
        run: |
          cd hyperos_port
          aria2c -s10 -x10 "${{ github.event.inputs.STOCK_URL }}" -o ./1.zip
          aria2c -s10 -x10 "${{ github.event.inputs.PORT_URL }}" -o ./2.zip
          sudo bash port.sh ./1.zip ./2.zip | tee HyperOS_portlog.log
      - name: 4.上传到 OneDrive
        run: |
            cd ${{ github.workspace }}
            touch info.md
            echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
            echo "移植底包链接：${{ github.event.inputs.STOCK_URL }}" >> info.md
            echo "移植机型链接：${{ github.event.inputs.PORT_URL }}" >> info.md
            echo "tosasitill made with love 0202 & 0227" >> info.md
            echo "文件名：$name" >> info.md
            curl -k -F "file=@/home/runner/work/hyperos_action/hyperos_action/hyperos_port/out/1.zip" -F "token=${{ secrets.RECLONE }}" -F "model=0"  -X POST "https://tmp-cli.vx-cdn.com/app/upload_cli"
      - name: 5.发布完成 Release
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "/home/runner/work/hyperos_action/hyperos_action/hyperos_port/HyperOS_portlog.log"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: 5.上传移植LOG
        uses: actions/upload-artifact@v4
        with:
          name: HyperOS-PortLOG
          path: "/home/runner/work/hyperos_action/hyperos_action/hyperos_port/HyperOS_portlog.log"
          compression-level: 9
